apiVersion: v1
kind: Pod
metadata:
  name: nfs-test
spec:
  containers:
    - name: nfs-test
      image: busybox:stable
      command:
        - /bin/sh
        - -c
        - "while true; do echo \"$(date) - writing from $(hostname)\" >> /mnt/nfs/test.log; sleep 5; done"
      volumeMounts:
        - name: nfs-vol
          mountPath: /mnt/nfs
  volumes:
    - name: nfs-vol
      persistentVolumeClaim:
        claimName: pvc-nfs-dynamic   # <-- change if your PVC has a different name
